### PR TITLE
Fix for results with no blocks, no animation on table scroll.

### LINKED ISSUE #362: Running workspace with no blocks crashes
After incorporating #344, running a workspace that contains no blocks makes the UI crash.

### PR DESCRIPTION
**Pull request by DarkMetroid**

### CODE REVIEW

File: libs/ui/tabs.jsx [hunk 1]
```diff
@@ -187,14 +187,23 @@ export function TabPanels (props) {
...
+                      rows={props.data}
+                      enableCellAutoFocus={false}
+                      height={props.topRightPaneHeight}
+                      onGridSort={props.sortRows}
+                      />
+                    :
+                      <div className="emptyPanelWrapper">
+                        <FontAwesomeIcon className="panelIcon"icon={faDatabase} />
+                        <p className="emptyPanelText">You aren't currently displaying any data.</p>
+                        <p className="emptyPanelText"> To learn more about getting started visit&nbsp;<a href="/guide/" className="guideLink">our guide</a>.
```
Comment (gvwilson) [inline libs/ui/tabs.jsx]: The absolute URL `/guide/` won't resolve for international versions: I think it wants to be `./guide/` to be relative to the language.

File: libs/ui/tabs.jsx [hunk 2]
```diff
@@ -222,14 +231,23 @@ export function TabPanels (props) {
...
+                      rows={props.results}
+                      enableCellAutoFocus={false}
+                      height={props.topRightPaneHeight}
+                      onGridSort={props.sortRows}
+                      />
+                  :
+                    <div className="emptyPanelWrapper">
+                      <FontAwesomeIcon className="panelIcon"icon={faDatabase} />
+                      <p className="emptyPanelText">You aren't currently displaying any results.</p>
+                      <p className="emptyPanelText"> To learn more about getting started visit&nbsp;<a href="/guide/" className="guideLink">our guide</a>.
```
Comment (gvwilson) [inline libs/ui/tabs.jsx]: As above, `/guide/` won't resolve for international versions.
